server.port=8080
app.cors.allowed-origins="http://localhost:8080","http://localhost:9090"
###### DATABASE CONFIG #########################
spring.datasource.url=jdbc:h2:mem:~
spring.datasource.driver-class-name=org.h2.Driver
############# JPA CONFIG ########################
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
telegram.bot.token=****************************************
telegram.bot.chatID=**********